#!/usr/bin/env zsh
clear
echo -e ""
echo -e ""
echo -e ""
echo -e ""
echo -e ""
echo -e ""
echo -e ""
echo -e ""
echo -e ""
echo -e ""
echo -e ""
echo -e "                               ▄▄▄▄▄▄▄▄▄             "
echo -e "                      ▄▄████▀▀▀▀▀      ▀▀█▄▄         "
echo -e "                   ▄██▀▀                  ▀██▄       "
echo -e "                  ▄█▀                        ▀█▄     "
echo -e "                 ██                           ▀█▄    "
echo -e "                ██                             ▀█▄   "
echo -e "                ██                         ▄▄▄  ▀█            ╔═╗╦ ╦╦ ╦╦ ╦╦ ╦"
echo -e "                █                          ▀██▄  ██           ╠╣ ║ ║║ ║║ ║║ ║"
echo -e "                █     ████                        █▄          ╚  ╚═╝╚═╝╚═╝╚═╝"
echo -e "                █     ▀▀▀█                        ██ "
echo -e "                █                       ▄▄▄▄█████▀ █▄"
echo -e "                █          ▄▄▄▄▄██████▀▀▀▀▀▀       ██"
echo -e "                █    ▄█████▀▀▀▀▀ ▄▄▄████           ██      Geolocalização não é GARANTIDA"
echo -e "                ██                ▀                ██"
echo -e "                ▀█▄                                █▀"
echo -e "                 ▀█                               ▄█ "
echo -e "                  ██                              ██ "
echo -e "                   ██                            ▄█  "
echo -e "                    ▀██▄                      ▄▄█▀   "
echo -e "                      ▀██▄                 ▄▄█▀      "
echo -e "                         ▀██▄           ▄▄█▀         "
echo -e "                            ▀██▄▄▄▄▄▄▄▄█▀            "
echo -e "                                  █                  "
echo -e "                                  █                  "
echo -e "                                  █                  "
echo -e "                                  █                  "
echo -e "                                  █                  "
echo -e "                                  █                  "
read slide
source slides/slide4.sh